/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SektorSectorRouteImport } from './routes/sektor/$sector'
import { Route as RegulasiTypeSlugRouteImport } from './routes/regulasi/$type.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SektorSectorRoute = SektorSectorRouteImport.update({
  id: '/sektor/$sector',
  path: '/sektor/$sector',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulasiTypeSlugRoute = RegulasiTypeSlugRouteImport.update({
  id: '/regulasi/$type/$slug',
  path: '/regulasi/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/search': typeof SearchRoute
  '/sektor/$sector': typeof SektorSectorRoute
  '/regulasi/$type/$slug': typeof RegulasiTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/search': typeof SearchRoute
  '/sektor/$sector': typeof SektorSectorRoute
  '/regulasi/$type/$slug': typeof RegulasiTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/search': typeof SearchRoute
  '/sektor/$sector': typeof SektorSectorRoute
  '/regulasi/$type/$slug': typeof RegulasiTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/search'
    | '/sektor/$sector'
    | '/regulasi/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect' | '/search' | '/sektor/$sector' | '/regulasi/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/search'
    | '/sektor/$sector'
    | '/regulasi/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  SearchRoute: typeof SearchRoute
  SektorSectorRoute: typeof SektorSectorRoute
  RegulasiTypeSlugRoute: typeof RegulasiTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sektor/$sector': {
      id: '/sektor/$sector'
      path: '/sektor/$sector'
      fullPath: '/sektor/$sector'
      preLoaderRoute: typeof SektorSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulasi/$type/$slug': {
      id: '/regulasi/$type/$slug'
      path: '/regulasi/$type/$slug'
      fullPath: '/regulasi/$type/$slug'
      preLoaderRoute: typeof RegulasiTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  SearchRoute: SearchRoute,
  SektorSectorRoute: SektorSectorRoute,
  RegulasiTypeSlugRoute: RegulasiTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
